name: Download, Process and Upload YouTube Videos

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'Folder name to save the videos'
        required: true
        default: 'youtube_videos'
      playlist_url:
        description: 'YouTube playlist URL'
        required: true
      resolution:
        description: 'Video resolution (e.g., 720p, 1080p)'
        required: true
        default: '720p'
      playback_speed:
        description: 'Playback speed (e.g., 1.0, 1.25, 1.5)'
        required: false
        default: '1.0'

jobs:
  download-and-process:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        pip install yt-dlp

    - name: Create output directory
      run: mkdir -p "${{ github.event.inputs.folder_name }}"

    - name: Download videos
      run: |
        python -c "
        import subprocess
        import os
        
        folder_name = '${{ github.event.inputs.folder_name }}'
        playlist_url = '${{ github.event.inputs.playlist_url }}'
        resolution = '${{ github.event.inputs.resolution }}'
        
        # Download command
        command = [
            'yt-dlp',
            '-o', f'{folder_name}/%(title)s.%(ext)s',
            '-f', f'bv*[ext=mp4][vcodec=h264][height<={resolution}]+ba[ext=m4a]/b[ext=mp4]',
            '--merge-output-format', 'mp4',
            playlist_url
        ]
        
        print('Downloading videos...')
        subprocess.run(command, check=True)
        print('Download completed.')
        "

    - name: Process videos for playback speed
      if: ${{ github.event.inputs.playback_speed != '1.0' }}
      run: |
        python -c "
        import subprocess
        import os
        
        folder_name = '${{ github.event.inputs.folder_name }}'
        playback_speed = '${{ github.event.inputs.playback_speed }}'
        speed_factor = float(playback_speed)
        pts_factor = 1.0 / speed_factor
        
        print(f'Adjusting playback speed to {playback_speed}x...')
        
        # Process each MP4 file in the folder
        for filename in os.listdir(folder_name):
            if filename.endswith('.mp4'):
                input_path = os.path.join(folder_name, filename)
                temp_path = os.path.join(folder_name, 'temp_' + filename)
                
                # Apply speed adjustment with ffmpeg
                ffmpeg_command = [
                    'ffmpeg',
                    '-i', input_path,
                    '-filter:v', f'setpts={pts_factor}*PTS',
                    '-filter:a', f'atempo={speed_factor}',
                    '-c:v', 'libx264',
                    '-c:a', 'aac',
                    '-b:a', '128k',
                    temp_path,
                    '-y'
                ]
                
                subprocess.run(ffmpeg_command, check=True)
                
                # Replace original with processed version
                os.remove(input_path)
                os.rename(temp_path, input_path)
                
                print(f'Processed: {filename}')
        
        print('Speed adjustment completed.')
        "

    - name: Zip processed videos
      run: |
        zip -r "${{ github.event.inputs.folder_name }}.zip" "${{ github.event.inputs.folder_name }}"/

    - name: Upload processed videos as artifact
      uses: actions/upload-artifact@v4
      with:
        name: processed-videos
        path: ${{ github.event.inputs.folder_name }}.zip

  create-release:
    needs: download-and-process
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: processed-videos
        path: .

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: youtube-videos-$(date +'%Y%m%d%H%M%S')
        name: YouTube Videos - $(date +'%Y-%m-%d %H:%M')
        body: |
          Processed YouTube videos with the following settings:
          - Folder name: ${{ github.event.inputs.folder_name }}
          - Resolution: ${{ github.event.inputs.resolution }}
          - Playback speed: ${{ github.event.inputs.playback_speed }}x
        draft: false
        prerelease: false
        files: ${{ github.event.inputs.folder_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
