name: Video Processor and Publisher

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Direct download URL of the video'
        required: true
        type: string
      playback_speed:
        description: 'Desired playback speed (e.g., 1.5 for 1.5x)'
        required: true
        type: number
        default: 1.5

jobs:
  process-video:
    runs-on: ubuntu-latest
    timeout-minutes: 120 # Timeout badha do agar videos bade honge

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg wget

    - name: Download video from provided URL
      run: |
        wget -O original_video.mp4 "${{ github.event.inputs.video_url }}"

    - name: Calculate FFmpeg filter values
      shell: bash
      run: |
        # Video speed calculation: 1 / desired speed
        VIDEO_SPEED=$(echo "1 / ${{ github.event.inputs.playback_speed }}" | bc -l)
        echo "VIDEO_FILTER=setpts=${VIDEO_SPEED}*PTS" >> $GITHUB_ENV
        echo "AUDIO_FILTER=atempo=${{ github.event.inputs.playback_speed }}" >> $GITHUB_ENV

    - name: Process video with FFmpeg
      run: |
        ffmpeg -i original_video.mp4 \
        -filter_complex "[0:v]${VIDEO_FILTER}[v];[0:a]${AUDIO_FILTER}[a]" \
        -map "[v]" -map "[a]" \
        -c:v libx264 -preset medium -crf 23 \
        -c:a aac -b:a 128k \
        -movflags +faststart \
        processed_video.mp4

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: video-${{ github.run_id }}
        release_name: Processed Video (${{ github.event.inputs.playback_speed }}x)
        draft: false
        prerelease: false

    - name: Upload Processed Video
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./processed_video.mp4
        asset_name: processed_video.mp4
        asset_content_type: video/mp4

    - name: Cleanup original video
      run: |
        rm -f original_video.mp4
