name: Video Processor and Publisher

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Direct download URL of the video'
        required: true
        type: string
      playback_speed:
        description: 'Desired playback speed (e.g., 1.5 for 1.5x)'
        required: true
        type: number
        default: 1.5
      release_name:
        description: 'Release Name'
        required: true
        type: string

permissions:
  contents: write

jobs:
  process-video:
    runs-on: ubuntu-latest
    timeout-minutes: 240

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg wget bc

    - name: Extract filename from URL
      shell: bash
      run: |
        # Extract the base filename from the URL
        FILENAME=$(basename "${{ github.event.inputs.video_url }}" | cut -d'?' -f1)
        # If the filename doesn't end with .mp4, default to 'video.mp4'
        if [[ ! "$FILENAME" =~ \.mp4$ ]]; then
          FILENAME="video.mp4"
        fi
        echo "ORIGINAL_FILENAME=$FILENAME" >> $GITHUB_ENV
        # Create the processed filename by inserting speed before the .mp4 extension
        PROCESSED_FILENAME="${FILENAME%.mp4}_${{ github.event.inputs.playback_speed }}x.mp4"
        echo "PROCESSED_FILENAME=$PROCESSED_FILENAME" >> $GITHUB_ENV

    - name: Download video from provided URL
      run: |
        wget -O "$ORIGINAL_FILENAME" "${{ github.event.inputs.video_url }}"

    - name: Process video with FFmpeg (TV Compatible with Speed Change)
      run: |
        ffmpeg -i "$ORIGINAL_FILENAME" -filter_complex "[0:v]setpts=0.6666666666*PTS[v];[0:a]atempo=${{ github.event.inputs.playback_speed }}[a]" -map "[v]" -map "[a]" -c:v libx264 -profile:v main -level 4.0 -pix_fmt yuv420p -c:a aac -b:a 128k -movflags +faststart output_video.mp4

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: video-${{ github.run_id }}
        name: "${{ github.event.inputs.release_name }}"
        body: |
          - ${{ github.event.inputs.release_name }} processed at ${{ github.event.inputs.playback_speed }}x speed
          - Processed on: ${{ github.event.inputs.playback_speed }}
        files: output_video.mp4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Cleanup
      run: |
        rm -f "$ORIGINAL_FILENAME" output_video.mp4
